# Configuration for AutogenRepoDocumentationGenerator

# OpenAI API settings
seed: 42
temperature: 0.5
max_api_calls_per_minute: 60

# Repository settings
repo_path: "tests"  # Path to the repository to analyze
